package veniceai_test

import (
	"context"
	"fmt"
	"log"
	"net/http"

	veniceai "github.com/13rac1/veniceai-go"
	"github.com/13rac1/veniceai-go/venicegen"
	openai "github.com/openai/openai-go/v3"
)

// ExampleClient_ChatComplete shows how to make a chat completion request with
// Venice-specific parameters for web search and system prompt control. Response
// headers expose balance and rate limit information.
func ExampleClient_ChatComplete() {
	client, err := veniceai.NewClient("your-api-key")
	if err != nil {
		log.Fatal(err)
	}

	result, err := client.ChatComplete(context.Background(), &openai.ChatCompletionNewParams{
		Model: "llama-3.3-70b",
		Messages: []openai.ChatCompletionMessageParamUnion{
			openai.UserMessage("What is Venice?"),
		},
	}, &veniceai.VeniceParameters{
		EnableWebSearch:           veniceai.Ptr(veniceai.WebSearchOn),
		IncludeVeniceSystemPrompt: veniceai.Ptr(false),
	})
	if err != nil {
		log.Fatal(err)
	}

	fmt.Println(result.Choices[0].Message.Content)
	fmt.Println("Balance:", result.Headers.BalanceDiem)
}

// ExampleClient_ChatCompleteStream shows how to consume a streaming chat
// completion. Pass nil for veniceParams to make a standard OpenAI-compatible
// request. Response headers are available on the stream before iteration begins.
func ExampleClient_ChatCompleteStream() {
	client, err := veniceai.NewClient("your-api-key")
	if err != nil {
		log.Fatal(err)
	}

	stream := client.ChatCompleteStream(context.Background(), &openai.ChatCompletionNewParams{
		Model: "llama-3.3-70b",
		Messages: []openai.ChatCompletionMessageParamUnion{
			openai.UserMessage("Tell me about Venice"),
		},
	}, nil)

	fmt.Println("Remaining requests:", stream.Headers.RateLimitRequestsRemaining)

	for stream.Next() {
		fmt.Print(stream.Current().Choices[0].Delta.Content)
	}
	if err := stream.Err(); err != nil {
		log.Fatal(err)
	}
}

// Example_imageGeneration shows how to generate an image using the
// Venice-specific GenerateImage endpoint via the Client.API field.
func Example_imageGeneration() {
	client, err := veniceai.NewClient("your-api-key")
	if err != nil {
		log.Fatal(err)
	}

	resp, err := client.API.GenerateImageWithResponse(context.Background(), nil, venicegen.GenerateImageJSONRequestBody{
		Model:  "fluently-xl",
		Prompt: "a cat in space",
	})
	if err != nil {
		log.Fatal(err)
	}
	if resp.StatusCode() != http.StatusOK {
		log.Fatalf("unexpected status: %s", resp.Status())
	}

	// JSON200 is the parsed response body for a 200 status, generated by oapi-codegen.
	fmt.Println("Generated", len(resp.JSON200.Images), "image(s)")
	fmt.Printf("Inference took %.2fs\n", resp.JSON200.Timing.Total)
}
